binaries=generator checker solver

# if using custom grader
binaries+=grader
binaries+=solver-juha
binaries+=solver-random
binaries+=brute

BASE_PATH=$(shell git rev-parse --show-toplevel)

include $(BASE_PATH)/common/Makefile.include

