binaries=generator checker solver

# if using custom grader
binaries+=grader
binaries+=solvernaive
binaries+=solver-juha

BASE_PATH=$(shell git rev-parse --show-toplevel)

include $(BASE_PATH)/common/Makefile.include

